#!/bin/bash

# navigation
  alias sam='goto ~/starry/amp starry'
  alias sce='goto ~/starry/cloud-env starry'
  alias sls='goto ~/starry/locksmith starry'
  alias sjv='goto ~/starry/jarvis starry'
  alias spp='goto ~/starry/pepper starry'
  alias ssa='goto ~/starry/sage starry'
  alias szl='goto ~/starry/ziploc starry'
  alias saa='goto ~/starry/admin-api-v2 starry'
  alias sap='goto ~/starry/auth-proxy starry'
  alias sca='goto ~/starry/cloud-api starry'
  alias srs='goto ~/starry/radius-server starry'

# git
  alias gcd='git checkout develop'

# mongo
  alias smongo='docker exec -it $(docker ps -aqf "name=cloud-env_mongodb_1") mongo jarvisdev'

# other
