#!/bin/bash

function source_if_exists () {
  path="${1?Must pass a path to source_if_exists}"
  if [[ -f "$path" ]]; then
    . "$path"
  fi
}

function goto() {
  export AWS_PROFILE=${2:-default}
  cd ${1} && echo -ne "\033]0;"${1}"\007"
}
