#!/bin/bash

NVM_DIR=~/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Automatically switch to node version specified in local dir's package.json (don't do this when in node_modules)
function autoswitch_to_node_version() {
  if [ -f 'package.json' ] && [[ "$PWD" != *'node_modules'* ]]; then
    requested_node_version="v$(node -p "(require('./package.json').engines || {}).node || ''")"
    if [ $requested_node_version == 'v' ]; then
      # local package.json does not have an engines.node value
      return 0;
    fi
    current_node_version="$(nvm current)"
    if [ "$requested_node_version" != "$current_node_version" ]; then
      # printf "requested_node_version: $requested_node_version\ncurrent_node_version: $current_node_version\n"
      nvm use
    fi
  fi
}
cd () { builtin cd "$@" && autoswitch_to_node_version; }
pushd () { builtin pushd "$@" && autoswitch_to_node_version; }
popd () { builtin popd "$@" && autoswitch_to_node_version; }
cd .

export NODE_PATH="/Users/edwmurph/.nvm/versions/node/v11.3.0/lib/node_modules"

[[ "$PATH" == *"./node_modules/.bin"* ]] || PATH="$PATH:./node_modules/.bin"
PATH="$PATH:/Users/edwmurph/.nvm/versions/node/v11.3.0/lib/node_modules"

