#!/bin/bash

source_if_exists ~/.secrets/.secrets

export CQLSH_NO_BUNDLED=true

### atlas
export WX2_ADMIN_WEB_CLIENT_HOME=/Users/eddie/code/wx2-admin-web-client
[[ "$PATH" == *"$HOME/code/wx2-admin-web-client/bin"* ]] || export PATH="$PATH:$HOME/code/wx2-admin-web-client/bin"

### Aliases

alias ca='cd ~/code/care-assistant && echo -ne "\033]0;"~/code/care-assistant"\007"'
alias va='cd ~/code/virtual-assistant && echo -ne "\033]0;"~/code/virtual-assistant"\007"'
alias an='cd ~/code/answers && echo -ne "\033]0;"~/code/answers"\007"'
alias vac='cd ~/code/virtual-assistant-common && echo -ne "\033]0;"~/code/virtual-assistant-common"\007"'
alias 2c='cd ~/code/2ca && echo echo -ne "\033]0;"~/code/2ca"\007"'
alias at='cd ~/code/wx2-admin-web-client && echo -ne "\033]0;"~/code/wx2-admin-web-client"\007"'
alias sms='cd ~/code/standalone-metrics-server && echo -ne "\033]0;"~/code/standalone-metrics-server"\007"'
alias ea='cd ~/code/expert-assistant && echo -ne "\033]0;"~/code/expert-assistant"\007"'
alias np='cd ~/code/node-pipeline && echo -ne "\033]0;"~/code/node-pipeline"\007"'
alias cal='cd ~/code/ca-loadrunner && echo -ne "\033]0;"~/code/ca-loadrunner"\007"'
alias al='cd ~/code/alfred && echo -ne "\033]0;"~/code/alfred"\007"'
alias cms='cd ~/code/ca-mock-spark && echo -ne "\033]0;"~/code/ca-mock-spark"\007"'
alias mm='cd ~/code/media-manager && echo -ne "\033]0;"~/code/media-manager"\007"'
alias cato='cd ~/code/ca-tools && echo -ne "\033]0;"~/code/ca-tools"\007"'
alias cc='cd ~/code/contact-center && echo -ne "\033]0;"~/code/contact-center"\007"'
alias cfappstaging="cf login -a https://api.appstaging.ciscoccservice.com -u admin -p ${CF_PW}"
alias cfloadus1="cf login -a https://api.loadus1.ciscoccservice.com -u admin -p ${CF_PW}"
alias cfdevus1="cf login -a https://api.devus1.ciscoccservice.com -u admin -p ${CF_PW}"

# Connect to cisco's vpn through anyconnect
# Expects MobilePASS token immediately after being called
function vpnC() {
  # launchctl load /Library/LaunchDaemons/com.cisco.anyconnect.vpnagentd.plist 2> /dev/null
  read token
  printf "edwmurph\n${token}\ny\n" |
    /opt/cisco/anyconnect/bin/vpn -s connect 'Boxborough - SSL'
}


### Contact Center
export ARTIFACTORY_USER='edwmurph'
export ARTIFACTORY_API_KEY="${ARTIFACTORY_API_KEY}"
export SBT_OPTS='-XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=512M -XX:MetaspaceSize=256M -Xms2G -Xmx2G'
