#!/bin/bash

# navigation
  alias sam='goto ~/code/starry/amp'
  alias sce='goto ~/code/starry/cloud-env'
  alias sls='goto ~/code/starry/locksmith'
  alias sjv='goto ~/code/starry/jarvis'
  alias spp='goto ~/code/starry/pepper'
  alias ssa='goto ~/code/starry/sage'
  alias szl='goto ~/code/starry/ziploc'
  alias saa='goto ~/code/starry/admin-api-v2'
  alias sap='goto ~/code/starry/auth-proxy'
  alias sca='goto ~/code/starry/cloud-api'
  alias srs='goto ~/code/starry/radius-server'
  alias scm='goto ~/code/starry/cloud-models'

# git
  alias gcd='git checkout develop'

# mongo
  alias smongo='docker exec -it $(docker ps -aqf "name=cloud-env_mongodb_1") mongo jarvisdev'
  alias smongo2='docker exec -it $(docker ps -aqf "name=cloud-env_mongodb_1") /bin/bash'

# other
  alias saat='cp ~/code/starry/admin-api-v2/local/template.vue ~/code/starry/admin-api-v2/lib/public/js/bundles/pings/pages/create.vue'
