#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####

# ln -s ${HOME}/code/personal/configs/dotfiles/zshrc ${HOME}/.zshrc

# tab completion
autoload -Uz compinit && compinit

eval "$(/opt/homebrew/bin/brew shellenv)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

CONFIGS_PATH="${HOME}/code/personal/configs"
SECRETS_PATH="${HOME}/.secrets"

. "${SECRETS_PATH}/secrets.zsh"
. "${CONFIGS_PATH}/zsh/init/init.zsh"

for file in $CONFIGS_PATH/zsh/**/*(.); do
  local name=$(echo "$file" | sed -e "s~^$CONFIGS_PATH/zsh/~~")

  if ! [[ $name = init/* ]] && [[ $name == *.zsh ]]; then
    . "$file"
  fi
done

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/emurphy/dev/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/emurphy/dev/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/emurphy/dev/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/emurphy/dev/google-cloud-sdk/completion.zsh.inc'; fi

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
