# ln -s ${HOME}/code/personal/configs/dotfiles/zshrc ${HOME}/.zshrc

export ZSH="/Users/emurphy/.oh-my-zsh"

# ZSH_THEME="Avit"
ZSH_CUSTOM="${HOME}/code/personal/configs/zsh_custom"

plugins=(git helpers prompt configs aliases funcs bf starry context)

source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/emurphy/dev/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/emurphy/dev/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/emurphy/dev/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/emurphy/dev/google-cloud-sdk/completion.zsh.inc'; fi
